# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Urlbox < Formula
  desc "Official CLI for the Urlbox screenshot and web automation API"
  homepage "https://urlbox.com"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/urlbox/urlbox-cli/releases/download/v0.10.0/urlbox_0.10.0_darwin_amd64.tar.gz"
      sha256 "9eccc047da7115b22a4b305a822cd27a0fb048a6e2c75709315a66622f07155b"

      define_method(:install) do
        bin.install "urlbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/urlbox/urlbox-cli/releases/download/v0.10.0/urlbox_0.10.0_darwin_arm64.tar.gz"
      sha256 "c12c269c97b71e2b612f40396cca7c25c90282139df27ff44d71cffcc40bf742"

      define_method(:install) do
        bin.install "urlbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/urlbox/urlbox-cli/releases/download/v0.10.0/urlbox_0.10.0_linux_amd64.tar.gz"
      sha256 "39f2862046a0714da1d6aaeedcb778718fc8a195f0348bcabef5392e4742b812"
      define_method(:install) do
        bin.install "urlbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/urlbox/urlbox-cli/releases/download/v0.10.0/urlbox_0.10.0_linux_arm64.tar.gz"
      sha256 "a164526a39e8bd67ba33dea77a9d68f0857a46e7f2b0349b9a413bcaa2a85114"
      define_method(:install) do
        bin.install "urlbox"
      end
    end
  end
end
