# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Urlbox < Formula
  desc "Official CLI for the Urlbox screenshot and web automation API"
  homepage "https://urlbox.com"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/urlbox/urlbox-cli/releases/download/v0.2.0/urlbox_0.2.0_darwin_amd64.tar.gz"
      sha256 "d099af8f64d158cd4303bf140bc3744eec3306b968408bd2f6884d4d0bfebc0e"

      define_method(:install) do
        bin.install "urlbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/urlbox/urlbox-cli/releases/download/v0.2.0/urlbox_0.2.0_darwin_arm64.tar.gz"
      sha256 "61cd0c50a5a7d89de58d9f5de958ed0c1f9bc998ecac2dbb73f5e57584bda6ce"

      define_method(:install) do
        bin.install "urlbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/urlbox/urlbox-cli/releases/download/v0.2.0/urlbox_0.2.0_linux_amd64.tar.gz"
      sha256 "90f3832245a9c7e483ff8f1c17cc914b9bdceba329c9157ba6a9fd896c90cd7a"
      define_method(:install) do
        bin.install "urlbox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/urlbox/urlbox-cli/releases/download/v0.2.0/urlbox_0.2.0_linux_arm64.tar.gz"
      sha256 "4a8a9954b223b200aa774a884ee3022dd3861da1cb21cd3012cbc11dab8fa629"
      define_method(:install) do
        bin.install "urlbox"
      end
    end
  end
end
