# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlbox" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "2c5f510b094253e07feb081255f956b76b9d0209cdbda8184fd5a1fa8c5e331f"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "94d2c18e8f1619d0b2871935c10929f65bc3a13548ec66dbaa8ced05b3babd6d"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "153092208f0794a68e4a904889ff4fbb0e182ae960b5c05184945fcb00e0e339"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a9d950775dff4babaa06cc61692b56ba4ea270ec0343b36537655f505b1af0ed"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "urlbox"
  desc "Official CLI for the Urlbox screenshot and web automation API"
  homepage "https://urlbox.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlbox"

  # No zap stanza required

end
