# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlbox" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a43424f42fd55a2ef79fcb49ec89e196cfbd4b76f78e40316281297815762c6f"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2fb92ca1eb55d6d03289ceb2a16e859411e3afd4866e89782a30d65a02d87013"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "caabca0c90762a7bd3d241463d6c371b41bfacdd95c1c16157b46f7397b609a3"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f3bfc48985145c508e53a25883c7dee368ea42d9d3e16417bf3fa454e3e58831"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "urlbox"
  desc "Official CLI for the Urlbox screenshot and web automation API"
  homepage "https://urlbox.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlbox"

  # No zap stanza required

end
