# This file was generated by GoReleaser. DO NOT EDIT.
cask "urlbox" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9c2e897fc72159bde30aaf9c70a01f5a9e08741f6425d02ecff5e0012ae9be86"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e1a730e43da28b83211a715e88afd764c12955b55ff58e27786caf41f6454651"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "50d81b8ac66a1b0a9d74e149f9c086a7147c5cef2b9c377139a853b8394c102d"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6eff2dbd29c96bc57396db62e3e0d1433a60d14661499381e20bdc7b923bc9a1"
      url "https://github.com/urlbox/urlbox-cli/releases/download/v#{version}/urlbox_#{version}_linux_arm64.tar.gz"
    end
  end

  name "urlbox"
  desc "Official CLI for the Urlbox screenshot and web automation API"
  homepage "https://urlbox.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "urlbox"

  # No zap stanza required

end
